# .scrutinizer.yml

build:

    dependencies:
        before:
            - rm composer.lock

    nodes:
        php70:
            environment:
                php:
                    version: 7.0.20 # Common versions: 5.4, 5.5, 5.6, 7.1 or hhvm

            tests:
                override:
                    -
                        command: 'vendor/bin/phpunit --coverage-clover=coverage'
                        coverage:
                            file: 'coverage'
                            format: 'php-clover'

        php71:
            environment:
                php:
                    version: 7.1 # Common versions: 5.4, 5.5, 5.6, 7.1 or hhvm

            tests:
                override:
                    -
                        command: 'vendor/bin/phpunit --coverage-clover=coverage'
                        coverage:
                            file: 'coverage'
                            format: 'php-clover'

        php72:
            environment:
                php:
                    version: 7.2 # Common versions: 5.4, 5.5, 5.6, 7.1 or hhvm

            tests:
                override:
                    -
                        command: 'vendor/bin/phpunit --coverage-clover=coverage'
                        coverage:
                            file: 'coverage'
                            format: 'php-clover'

        php73:
            environment:
                php:
                    version: 7.3 # Common versions: 5.4, 5.5, 5.6, 7.1 or hhvm

            tests:
                override:
                    -
                        command: 'vendor/bin/phpunit --coverage-clover=coverage'
                        coverage:
                            file: 'coverage'
                            format: 'php-clover'


checks:
    php:
        code_rating: true
        duplication: true

filter:
    excluded_paths:
        - tests/*



